### ISSUE TITLE
How to use maven in anaconda virtual env?

### ISSUE THREAD

**Issue by whitelowrie** [shadaj/scalapy#146]
When I use maven manage the project, and python environment is anaconda virtual env, so i got this exception:

os: mac os
project manage: maven
environment: anaconda virtual env
ide: intellj idea
python3-config --configdir: /Users/fabinliu/.conda/envs/twork/lib/python3.6/config-3.6m-darwin
-Djava.library.path=/Users/xxx/.conda/envs/twork/lib/python3.6/config-3.6m-darwin

![image](https://user-images.githubusercontent.com/13913085/105317313-0691bd00-5bfd-11eb-8315-dca96c6339d8.png)

![image](https://user-images.githubusercontent.com/13913085/105317402-1f01d780-5bfd-11eb-9fe7-fb002e0f53be.png)

```java
	at me.shadaj.scalapy.interpreter.CPythonInterpreter$.<init>(CPythonInterpreter.scala:9)
	at me.shadaj.scalapy.interpreter.CPythonInterpreter$.<clinit>(CPythonInterpreter.scala)
	at me.shadaj.scalapy.py.package$.<init>(package.scala:15)
	at me.shadaj.scalapy.py.package$.<clinit>(package.scala)
	at com.tencent.akka.PyScala$.delayedEndpoint$com$tencent$akka$PyScala$1(PyScala.scala:7)
	at com.tencent.akka.PyScala$delayedInit$body.apply(PyScala.scala:6)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.tencent.akka.PyScala$.main(PyScala.scala:6)
	at com.tencent.akka.PyScala.main(PyScala.scala)
Caused by: java.lang.Exception: Unable to locate Python library, tried python3.6m, python3, python3.7, python3.7m
	at me.shadaj.scalapy.interpreter.CPythonAPIInterface$$anonfun$2.apply(CPythonAPI.scala:19)
	at me.shadaj.scalapy.interpreter.CPythonAPIInterface$$anonfun$2.apply(CPythonAPI.scala:19)
	at scala.Option.getOrElse(Option.scala:121)
	at me.shadaj.scalapy.interpreter.CPythonAPIInterface.<init>(CPythonAPI.scala:18)
	at me.shadaj.scalapy.interpreter.CPythonAPI$.<init>(CPythonAPI.scala:102)
	at me.shadaj.scalapy.interpreter.CPythonAPI$.<clinit>(CPythonAPI.scala)
	... 15 more
```

**Comment by shadaj** [comment]
@whitelowrie that's odd, can you verify that `java.library.path` contains the folder by printing it out before initializing ScalaPy? As long as the `dylib`/`so`/`dll` is on the path, JNA should pick itup.

**Comment by whitelowrie** [comment]
@shadaj thank you, I execute it success, well, I add these code
    System.setProperty("jna.library.path", "/Users/xxx/opt/anaconda3/lib/")
    System.setProperty("java.library.path", "/Users/xxx/opt/anaconda3/lib/")

**Comment by whitelowrie** [comment]
but other problem is the scalapy just adapter above scala 2.12，cloud you provide scala 2.11 in the maven repository, thanks a lot !!!

**Comment by jaroslawk** [comment]
@whitelowrie the issue which you had with IntelliJ is related to the weak support of SBT. It looks like IntelliJ do not respect updates of javaOpts in SBT:

`
javaOptions += s"-Djna.library.path=$pythonLibsDir"  
`

you need to manually pass the additional vm option under run config
