### ISSUE TITLE
`sbt runMain` not working for Scala Native

### ISSUE THREAD

**Issue by PawelLipski** [shadaj/scalapy#78]
Likely a different issue than https://github.com/shadaj/scalapy/issues/31:

`sbt 'project benchNative' 'runMain me.shadaj.scalapy.py.DataSendingBench'` ends up in:

```
[info] Loading global plugins from /home/pawellipski/.sbt/1.0/plugins
[info] Loading settings for project scalapy-build from plugins.sbt ...
[info] Loading project definition from /home/pawellipski/scalapy/project
[info] Loading settings for project scalapy from build.sbt,publish.sbt ...
[info] Set current project to scalapy (in build file:/home/pawellipski/scalapy/)
[info] Set current project to scalapy-bench (in build file:/home/pawellipski/scalapy/)
[info] Compiling 1 Scala source to /home/pawellipski/scalapy/coreMacros/.native/target/scala-2.11/classes ...
[warn] there were 5 deprecation warnings; re-run with -deprecation for details
[warn] one warning found
[info] Compiling 2 Scala sources to /home/pawellipski/scalapy/core/native/target/scala-2.11/classes ...
[info] running me.shadaj.scalapy.py.DataSendingBench 
[error] (run-main-0) scala.scalanative.runtime.UndefinedBehaviorError
[error] scala.scalanative.runtime.UndefinedBehaviorError
[error]         at scala.scalanative.runtime.package$.undefined(package.scala:34)
[error]         at scala.scalanative.native.package$.extern(package.scala:112)
[error]         at me.shadaj.scalapy.py.CPythonAPI$.Py_Initialize(CPythonAPI.scala:7)
[error]         at me.shadaj.scalapy.py.CPythonInterpreter$.<init>(CPythonInterpreter.scala:4)
[error]         at me.shadaj.scalapy.py.CPythonInterpreter$.<clinit>(CPythonInterpreter.scala)
[error] 	at me.shadaj.scalapy.py.package$.<init>(package.scala:12)
[error] 	at me.shadaj.scalapy.py.package$.<clinit>(package.scala)
[error] 	at me.shadaj.scalapy.py.DataSendingBench$$anonfun$1$$anonfun$apply$mcVI$sp$1.apply$mcV$sp(DataSendingBench.scala:9)
[error] 	at me.shadaj.scalapy.py.Bench$.test(Bench.scala:14)
[error] 	at me.shadaj.scalapy.py.DataSendingBench$$anonfun$1.apply$mcVI$sp(DataSendingBench.scala:5)
[error] 	at me.shadaj.scalapy.py.DataSendingBench$$anonfun$1.apply(DataSendingBench.scala:4)
[error] 	at me.shadaj.scalapy.py.DataSendingBench$$anonfun$1.apply(DataSendingBench.scala:4)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at me.shadaj.scalapy.py.DataSendingBench$.delayedEndpoint$me$shadaj$scalapy$py$DataSendingBench$1(DataSendingBench.scala:4)
[error] 	at me.shadaj.scalapy.py.DataSendingBench$delayedInit$body.apply(DataSendingBench.scala:3)
[error] 	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
[error] 	at scala.App$class.main(App.scala:76)
[error] 	at me.shadaj.scalapy.py.DataSendingBench$.main(DataSendingBench.scala:3)
[error] 	at me.shadaj.scalapy.py.DataSendingBench.main(DataSendingBench.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] stack trace is suppressed; run last Compile / bgRunMain for the full output
[error] Nonzero exit code: 1
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 14 s, completed 14 Jun 2020, 22:13:47
```

I can provide you @shadaj with more details about the environment if needed.

CC @Gryfit

**Comment by PawelLipski** [comment]
Use `sbt {projectName}/run <<< {class number}`, e.g. `sbt scalaPyTensorFlowCrossNative/run <<< 1`
